version: '3.8'

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - data_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: vkfedosov/api_yamdb:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx/templates/:/etc/nginx/templates
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    env_file:
      - ./.env
    depends_on:
      - web

volumes:
  data_value:
  static_value:
  media_value: