# Generated by Django 2.2.19 on 2022-09-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_auto_20220922_1350'),
        ('titles', '0007_auto_20220925_0325'),
    ]

    operations = [
    ]
