# Generated by Django 2.2.16 on 2022-09-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0010_auto_20220926_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
    ]
