# Generated by Django 2.2.16 on 2022-09-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0014_auto_20220926_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
