# Generated by Django 2.2.16 on 2022-12-15 09:44

import django.core.validators
from django.db import migrations, models
import titles.models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0016_auto_20220929_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=titles.models.get_current_year, message='Произведение еще не вышло!')]),
        ),
    ]
